# Create a password generator project:-- Easy level
import random

letters=['A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
numbers=['0','1','2','3','4','5','6','7','8','9']
symbols=['@','#','$','%','^','&','*','!','/']

print("Welcome to password generator!")
nr_letters=int(input("How many number of letters do you want to have in your password? "))
nr_symbols=int(input("How many number of symbols do you want in your password? "))
nr_numbers=int(input("How many number of digits do you want to have in your password? "))
password=" "
for char in range(1,nr_letters+1):
    random_char=random.choice(letters)
    password+=random_char

for char in range(1,nr_numbers+1):
    password+=random.choice(numbers)

for char in range(1,nr_symbols+1):
    password+=random.choice(symbols)

print(f"The password generated by you is : {password}")

#Hard level where password is shuffled:--
password_list=[]
for char in range(1,nr_letters+1):
    password_list.append(random.choice(letters))

for char in range(1,nr_numbers+1):
    password_list+=random.choice(numbers)

for char in range(1,nr_symbols+1):
    password_list+=random.choice(symbols)

print(password_list)
random.shuffle(password_list)
print(password_list)
password=" "
for char in password_list:
    password+=char
print(f"The password generated by you is: {password}")